services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
  
    env_file:
      - .env
    environment:
    
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"

    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    image: emrecyhn/assesment:latest
    restart: unless-stopped
    expose:
      - "3000"
   
    env_file:
      - .env
    environment:
      SEED_ON_START: "${SEED_ON_START:-true}"
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app


  postgres-dev-port:
    image: alpine/socat:1.8.0.0
    profiles: ["dev"]
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    command: TCP-LISTEN:5432,fork,reuseaddr TCP:postgres:5432
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
